class_name MapBuilder
extends RefCounted
## Builds a TileSet at runtime from placeholder PNGs and fills TileMapLayers
## from ASCII rows. When real tilesets arrive, this is replaced by authored
## TileSet resources — map layouts stay the same.

const TILE := 16

const TILE_TEXTURES := {
	"tile_grass": "res://assets/placeholder/tile_grass.png",
	"tile_grass_dark": "res://assets/placeholder/tile_grass_dark.png",
	"tile_soil_tilled": "res://assets/placeholder/tile_soil_tilled.png",
	"tile_soil_watered": "res://assets/placeholder/tile_soil_watered.png",
	"tile_stone_floor": "res://assets/placeholder/tile_stone_floor.png",
	"tile_wall": "res://assets/placeholder/tile_wall.png",
	"tile_water": "res://assets/placeholder/tile_water.png",
	"tile_path": "res://assets/placeholder/tile_path.png",
	"tile_sand": "res://assets/placeholder/tile_sand.png",
}

## V3 tile variety: each key in VARIANTS names a BASE tile from TILE_TEXTURES
## above; the array lists its extra, purely-cosmetic variant PNGs (index 0 is
## the base tile itself — see variant_for()'s "index 0 = base" contract — so
## these only need the ADDITIONAL textures, generated by
## tools/gen_placeholders.gd's _write_tile_variants()). Variants share their
## base's solidity (SOLID below is keyed by base name only) and collision
## shape — this is a pure re-skin, not a new gameplay tile.
const VARIANTS := {
	"tile_grass": [
		"res://assets/placeholder/tile_grass_var1.png",
		"res://assets/placeholder/tile_grass_var2.png",
		"res://assets/placeholder/tile_grass_var3.png",
	],
	"tile_soil_tilled": [
		"res://assets/placeholder/tile_soil_tilled_var1.png",
	],
	"tile_stone_floor": [
		"res://assets/placeholder/tile_stone_floor_var1.png",
	],
	"tile_sand": [
		"res://assets/placeholder/tile_sand_var1.png",
	],
}

## V3 scatter decoration: small transparent-background decal textures for
## MapDecoration's non-colliding overlay pass (grass tufts/flowers/pebbles
## scattered sparsely over outdoor maps — see map_decoration.gd). These are
## NOT in TILE_TEXTURES/VARIANTS (no ground tile fills them, no solidity, no
## variant_for() involvement) — a separate small source group on the SAME
## TileSet so DecalLayer can share build_tileset()'s output instead of
## building its own TileSet.
const DECAL_TEXTURES := {
	"decal_tuft": "res://assets/placeholder/decal_tuft.png",
	"decal_flower": "res://assets/placeholder/decal_flower.png",
	"decal_pebble": "res://assets/placeholder/decal_pebble.png",
}

const SOLID := ["tile_wall", "tile_water"]

const CHAR_TILES := {
	"G": "tile_grass",
	"D": "tile_grass_dark",
	"S": "tile_stone_floor",
	"W": "tile_wall",
	"~": "tile_water",
	"P": "tile_path",
	"A": "tile_sand",
}


static func build_tileset() -> Dictionary:
	var ts := TileSet.new()
	ts.tile_size = Vector2i(TILE, TILE)
	ts.add_physics_layer()
	# ids[base_name] stays a single int for every EXISTING caller (fill_layer's
	# non-variant path, FarmRenderer's soil lookup, tests) — variant source ids
	# live in a separate parallel dict so nothing that expects ids[name] to be
	# an int breaks. ids["__variants__"][base_name] is an Array of extra source
	# ids, index 0 == the first entry of VARIANTS[base_name] (base tile itself
	# is ids[base_name], never duplicated into the variants array).
	var ids := {}
	var variant_ids := {}
	for tile_name: String in TILE_TEXTURES:
		ids[tile_name] = _add_tile_source(ts, tile_name, TILE_TEXTURES[tile_name])
		if VARIANTS.has(tile_name):
			var extra_ids: Array = []
			for variant_path: String in VARIANTS[tile_name]:
				extra_ids.append(_add_tile_source(ts, tile_name, variant_path))
			variant_ids[tile_name] = extra_ids
	ids["__variants__"] = variant_ids
	for decal_name: String in DECAL_TEXTURES:
		ids[decal_name] = _add_tile_source(ts, decal_name, DECAL_TEXTURES[decal_name])
	return {"tileset": ts, "ids": ids}


static func _add_tile_source(ts: TileSet, tile_name: String, texture_path: String) -> int:
	var src := TileSetAtlasSource.new()
	src.texture = load(texture_path)
	src.texture_region_size = Vector2i(TILE, TILE)
	# ORDER MATTERS: the source must be added to the TileSet BEFORE
	# create_tile(), or TileData won't see the physics layer and
	# add_collision_polygon errors with "physics.size() = 0" (Godot 4.6).
	var id := ts.add_source(src)
	src.create_tile(Vector2i.ZERO)
	if tile_name in SOLID:
		var td := src.get_tile_data(Vector2i.ZERO, 0)
		td.add_collision_polygon(0)
		var h := TILE / 2.0
		td.set_collision_polygon_points(0, 0, PackedVector2Array([
			Vector2(-h, -h), Vector2(h, -h), Vector2(h, h), Vector2(-h, h),
		]))
	return id


## Deterministic per-cell variant pick: same (base_name, cell) ALWAYS returns
## the same source id, on every reload/save (no engine RNG, no cell-order
## dependence — just an integer hash of the cell coords). Cells with no
## registered variants (VARIANTS.has(base_name) == false) always return the
## base id, so callers can call this unconditionally for every ground tile.
static func variant_for(base_name: String, cell: Vector2i, ids: Dictionary) -> int:
	var base_id: int = ids.get(base_name, -1)
	var variants: Dictionary = ids.get("__variants__", {})
	var extra_ids: Array = variants.get(base_name, [])
	if extra_ids.is_empty():
		return base_id
	# Options are [base_id] + extra_ids so the plain, undecorated tile is
	# still in the rotation (most cells should stay a "plain" grass tile —
	# variants are meant to read as occasional flecks of variety, not a
	# wall-to-wall pattern).
	var options: Array = [base_id]
	options.append_array(extra_ids)
	var h := _cell_hash(cell)
	return options[h % options.size()]


## Stable 32-bit-ish hash of a cell — deliberately NOT Vector2i.hash() (that's
## an engine implementation detail, not a documented stable contract across
## Godot versions); this is our own small mix so the "same cell -> same
## variant, forever" promise doesn't depend on engine internals.
static func _cell_hash(cell: Vector2i) -> int:
	var h := (cell.x * 374761393 + cell.y * 668265263) & 0x7fffffff
	h = (h ^ (h >> 13)) & 0x7fffffff
	return h


static func fill_layer(layer: TileMapLayer, rows: PackedStringArray, ids: Dictionary) -> void:
	for y in rows.size():
		var row := rows[y]
		for x in row.length():
			var ch := row[x]
			if CHAR_TILES.has(ch):
				var base_name: String = CHAR_TILES[ch]
				var cell := Vector2i(x, y)
				layer.set_cell(cell, variant_for(base_name, cell, ids), Vector2i.ZERO)


static func cell_of(pos: Vector2) -> Vector2i:
	return Vector2i((pos / float(TILE)).floor())


static func cell_center(cell: Vector2i) -> Vector2:
	return Vector2(cell) * TILE + Vector2(TILE / 2.0, TILE / 2.0)


static func is_water_at(ground: TileMapLayer, cell: Vector2i) -> bool:
	## DEPTH stride (fishing): a runtime "is this cell water" query for a
	## built Ground TileMapLayer — used by FishingLogic.can_fish_at() to
	## gate casting on "facing water". Compares the cell's tile SOURCE
	## texture against tile_water.png's loaded resource (Godot caches
	## load() by path, so this is a reference-equality check, not a path
	## string compare) rather than requiring callers to thread the
	## build_tileset() ids dict through — a map script only ever hands
	## its Ground node to callers, never its ids dict.
	if ground == null or ground.tile_set == null:
		return false
	var source_id := ground.get_cell_source_id(cell)
	if source_id < 0:
		return false
	var source := ground.tile_set.get_source(source_id)
	if not (source is TileSetAtlasSource):
		return false
	var water_tex := load(TILE_TEXTURES["tile_water"])
	return (source as TileSetAtlasSource).texture == water_tex


static func solid_rect_for(center_px: Vector2, size_px: Vector2) -> Rect2i:
	## Alive Stride 1: converts a StaticBody2D-style centered collision box
	## (position in PIXELS, RectangleShape2D.size in PIXELS) into the Rect2i
	## of grid CELLS it overlaps — used by map scripts to feed PathGrid.build()
	## the same prop footprints (house/counter/hut/boat-shed/notice-board)
	## their own _add_props() already gives real collision to, so pathfinding
	## routes around exactly what the player's body already collides with.
	var top_left := center_px - size_px / 2.0
	var bottom_right := center_px + size_px / 2.0
	var start := cell_of(top_left)
	# Subtract an epsilon before flooring the far edge so an exact multiple of
	# TILE (e.g. a 32px-wide box starting on a tile boundary) doesn't pull in
	# one extra empty cell past the box's true edge.
	var end := cell_of(bottom_right - Vector2(0.01, 0.01))
	return Rect2i(start, end - start + Vector2i.ONE)
