class_name MapDecoration
extends RefCounted
## LOOK V3: deterministic scatter-decoration pass for outdoor maps (farm,
## town, riverwoods, beach). Paints sparse, non-colliding decals (grass
## tufts/flowers/pebbles) onto a dedicated TileMapLayer sitting between Ground
## and World, so the decals never affect collision/pathfinding and never
## y-sort against the player (they're flat ground clutter, like the
## soil/festival-decor overlay layers other maps already use).
##
## SEED RULE (documented per the stride contract): whether a given cell gets
## a decal, and WHICH decal it gets, is a pure function of that cell's own
## (x, y) coordinates via MapBuilder's cell hash — NOT of map id, NOT of
## Clock/day/season, NOT of engine RNG. This means:
##   - The exact same map always decorates identically on every load/save
##     (no persistence needed — it's regenerated by _ready() every time,
##     same as Ground itself).
##   - Two different maps that happen to share a cell coordinate will roll
##     the same decal/no-decal outcome there (acceptable: decoration is
##     cosmetic clutter, not a per-map identity).
## Density is DENSITY (see below) of ELIGIBLE cells only — eligible cells are
## caller-supplied (grass/dark-grass/sand cells only; never path/water/wall/
## stone/soil, and never a cell inside an `avoid` footprint like a prop, a
## portal, or a tilled/watered farm plot).

const DENSITY := 0.065  # ~6.5% of eligible cells get a decal (contract: 5-8%)

## Decal weight table: name -> relative pick weight (denser small tufts than
## the rarer flower/pebble accents, so the scatter reads as "grass with
## texture" rather than "grass covered in flowers").
const DECAL_WEIGHTS := {
	"decal_tuft": 5,
	"decal_flower": 2,
	"decal_pebble": 3,
}


## Builds the ordered [name, cumulative_weight] table once so
## _pick_decal_name() doesn't rebuild it per cell.
static func _weighted_names() -> Array:
	var names := DECAL_WEIGHTS.keys()
	names.sort()  # deterministic iteration order regardless of Dictionary internals
	return names


## Returns the sorted list of eligible cells that actually get a decal this
## pass — same (candidates, salt) always returns the same set (DENSITY-th
## fraction of candidates, chosen by per-cell hash against a threshold, not by
## shuffling — so adding/removing a FAR-AWAY candidate cell never reshuffles
## which nearby cells are decorated).
static func decorated_cells(candidates: Array, salt: int = 0) -> Array:
	var out: Array = []
	var threshold := int(DENSITY * float(0x7fffffff))
	for cell: Vector2i in candidates:
		if _salted_hash(cell, salt) < threshold:
			out.append(cell)
	return out


## Which decal a given (already-decided-to-decorate) cell gets — deterministic
## from the cell + salt, independent of decorated_cells' own threshold roll
## (a different salt offset keeps the two draws from correlating).
static func decal_for(cell: Vector2i, salt: int = 0) -> String:
	var names := _weighted_names()
	var total := 0
	for n: String in names:
		total += int(DECAL_WEIGHTS[n])
	var h := _salted_hash(cell, salt + 1000003)
	var roll := h % total
	var acc := 0
	for n: String in names:
		acc += int(DECAL_WEIGHTS[n])
		if roll < acc:
			return n
	return names[0]  # unreachable given the loop above sums to `total`, kept as a safe fallback


static func _salted_hash(cell: Vector2i, salt: int) -> int:
	return MapBuilder._cell_hash(Vector2i(cell.x + salt * 131, cell.y - salt * 197))


## Builds + fills a fresh decal TileMapLayer: `candidates` is the caller's
## list of eligible cells (grass/dark-grass/sand only, already excluding
## paths/water/props/portals/tilled plots — see each map script's
## _decoration_candidate_cells()), `tileset`/`ids` come from the SAME
## MapBuilder.build_tileset() call the map's Ground layer already uses (decal
## sources are registered there — see MapBuilder.DECAL_TEXTURES), and `salt`
## lets different maps avoid decorating identically at any SHARED cell
## coordinate space overlap (cosmetic only, not required for correctness).
static func build_layer(tileset: TileSet, ids: Dictionary, candidates: Array, salt: int = 0) -> TileMapLayer:
	var layer := TileMapLayer.new()
	layer.name = "Decoration"
	layer.tile_set = tileset
	for cell: Vector2i in decorated_cells(candidates, salt):
		var decal_name := decal_for(cell, salt)
		layer.set_cell(cell, ids[decal_name], Vector2i.ZERO)
	return layer
